### ISSUE TITLE
Add haploid label encoder 

### ISSUE THREAD

**Issue by rahulmohan** [clara-parabricks/VariantWorks#92]
Given a pileup generated from a truth sequence aligned to the draft sequence, generate one-hot encoded labels for each pileup column. The possible labels should be one of: [A, C, G, T, deletion], in both the forward and reverse strand. Therefore, given a pileup file as input, the output labels should be of shape (num_pileup_col, 10).

**Comment by tijyojwad** [comment]
Assigninhg to @rahulmohan

**Comment by tijyojwad** [comment]
Closing this with #120
